/**
 * breakpoints and number of columns for each screen size
 * desktop: 5
 * tablet: 3
 * mobile: 1
 */

export const PROFILE_LAYOUT_BREAKPOINTS = {
  lg: 1200,
  md: 996,
  sm: 768,
  xs: 480,
};
export const PROFILE_LAYOUT_COLUMNS = { lg: 5, md: 3, sm: 3, xs: 1 };

// initial layouts for react-grid-layout (desktop, tablet, mobile)
export const PROFILE_LAYOUT_DEFAULT = {
  lg: [
    { i: 'block-user', x: 0, y: 0, w: 2, h: 2, static: true },
    { i: 'block-nav', x: 2, y: 0, w: 3, h: 1, static: true },
    {
      i: 'block-sponsors',
      x: 2,
      y: 1,
      w: 3,
      h: 1,
      minW: 1,
      maxW: 4,
      minH: 1,
      maxH: 1,
    },
    {
      i: 'block-latest-post',
      x: 0,
      y: 2,
      w: 3,
      h: 1.5,
      minW: 2,
      maxW: 3,
      minH: 1.5,
      maxH: 1.5,
    },
    {
      i: 'block-now-playing',
      x: 3,
      y: 2,
      w: 2,
      h: 1.5,
      minW: 2,
      maxW: 2,
      minH: 1.5,
      maxH: 1.5,
    },
    {
      i: 'block-social-networks',
      x: 0,
      y: 4,
      w: 1,
      h: 1,
      minW: 1,
      maxW: 2,
      minH: 1,
      maxH: 1,
    },
    {
      i: 'block-achievements',
      x: 1,
      y: 4,
      w: 1,
      h: 1,
      minW: 1,
      maxW: 2,
      minH: 1,
      maxH: 1,
    },
    {
      i: 'block-gears',
      x: 2,
      y: 4,
      w: 2,
      h: 1,
      minW: 1,
      maxW: 3,
      minH: 1,
      maxH: 1,
    },

    {
      i: 'block-store',
      x: 4,
      y: 4,
      w: 1,
      h: 2,
      minW: 1,
      maxW: 2,
      minH: 2,
      maxH: 2,
    },
    {
      i: 'block-squad',
      x: 0,
      y: 6,
      w: 2,
      h: 1,
      minW: 1,
      maxW: 2,
      minH: 1,
      maxH: 1,
    },
  ],
  md: [
    { i: 'block-user', x: 0, y: 0, w: 2, h: 2, static: true },
    { i: 'block-nav', x: 2, y: 0, w: 1, h: 3, static: true },
    { i: 'block-sponsors', x: 0, y: 2, w: 3, h: 1, minW: 2, minH: 1, maxH: 1 },
    { i: 'block-achievements', x: 0, y: 3, w: 1, h: 2, minH: 2, maxH: 2 },
    {
      i: 'block-latest-post',
      x: 1,
      y: 3,
      w: 2,
      h: 2,
      minW: 2,
      minH: 2,
      maxH: 2,
    },
    { i: 'block-gears', x: 0, y: 5, w: 3, h: 1, minW: 2, minH: 1, maxH: 1 },
    { i: 'block-social-networks', x: 0, y: 8, w: 1, h: 1, minH: 1, maxH: 1 },
    { i: 'block-now-playing', x: 1, y: 8, w: 2, h: 2, minH: 2, maxH: 2 },
    { i: 'block-store', x: 4, y: 6, w: 1, h: 2, minH: 2, maxH: 2 },
    { i: 'block-squad', x: 0, y: 6, w: 1, h: 2, minW: 1, minH: 1, maxH: 2 },
  ],
  sm: [
    { i: 'block-user', x: 0, y: 0, w: 3, h: 2, static: true },
    { i: 'block-nav', x: 0, y: 2, w: 3, h: 1, static: true },
    { i: 'block-sponsors', x: 0, y: 3, w: 3, h: 1, minW: 2, minH: 1, maxH: 1 },
    { i: 'block-achievements', x: 0, y: 4, w: 1, h: 2, minH: 2, maxH: 2 },
    {
      i: 'block-latest-post',
      x: 1,
      y: 4,
      w: 2,
      h: 2,
      minW: 2,
      minH: 2,
      maxH: 2,
    },
    { i: 'block-gears', x: 0, y: 6, w: 3, h: 1, minW: 2, minH: 1, maxH: 1 },
    { i: 'block-social-networks', x: 0, y: 9, w: 1, h: 1, minH: 1, maxH: 1 },
    { i: 'block-now-playing', x: 1, y: 9, w: 2, h: 2, minH: 2, maxH: 2 },
    { i: 'block-store', x: 4, y: 6, w: 1, h: 2, minH: 2, maxH: 2 },
    { i: 'block-squad', x: 0, y: 6, w: 1, h: 2, minW: 1, minH: 1, maxH: 2 },
  ],
  xs: [
    { i: 'block-user', x: 0, y: 0, w: 1, h: 2, static: true },
    { i: 'block-nav', x: 0, y: 2, w: 1, h: 1, static: true },
    { i: 'block-sponsors', x: 0, y: 4, w: 1, h: 1, minH: 1, maxH: 1 },
    { i: 'block-achievements', x: 0, y: 4, w: 1, h: 2, minH: 2, maxH: 2 },
    {
      i: 'block-latest-post',
      x: 0,
      y: 6,
      w: 1,
      h: 2,
      minW: 2,
      minH: 2,
      maxH: 2,
    },
    { i: 'block-gears', x: 0, y: 8, w: 1, h: 1, minH: 1, maxH: 1 },
    { i: 'block-social-networks', x: 0, y: 9, w: 1, h: 1, minH: 1, maxH: 1 },
    { i: 'block-now-playing', x: 0, y: 12, w: 1, h: 2, minH: 2, maxH: 2 },
    { i: 'block-store', x: 4, y: 6, w: 1, h: 2, minH: 2, maxH: 2 },
    { i: 'block-squad', x: 0, y: 6, w: 1, h: 2, minW: 1, minH: 1, maxH: 2 },
  ],
};
