/**
 * Gamer One API Documentation
 * Welcome to the Official Gamer One API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@gamerone.gg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Badge } from './badge';

export type ActionType =
  | ''
  | 'up-vote'
  | 'comment'
  | 'experience'
  | 'follow'
  | 'follower'
  | 'post'
  | 'profile_complete'
  | 'signup'
  | 'game'
  | 'currently_playing'
  | 'sponsor'
  | 'socialNetwork'
  | 'store'
  | 'gear';

export interface Achievement {
  id: number;
  date: Date;
  badge: Badge | null;
  action: ActionType;
  threshold: number;
}
