/**
 * Gamer One API Documentation
 * Welcome to the Official Gamer One API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@gamerone.gg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
// import { PostClub } from './postClub';
import { PostUser } from './postUser';

export interface PagedPost {
  offset: number;
  posts: Array<PostUser>;
  // TOOD:
  // posts: Array<PostUser | PostClub>;
}
