/**
 * Gamer One API Documentation
 * Welcome to the Official Gamer One API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@g1.gg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Game } from './game';
import { PostMedia } from './postMedia';

export interface Post {
  id: number;
  title: string;
  description: string | null;
  image: string;
  url: string;
  html: string;
  privacy: string;
  commentsEnabled: boolean;
  isVoted: PostIsVoted;
  upCount: number;
  downCount: number;
  commentCount: number;
  createdAt: string;
  games: Array<Game>;
  images: Array<PostMedia>;
}
export type PostIsVoted = 'null' | 'up' | 'down';

export enum PostIsVotedEnum {
  Null = 'null',
  Up = 'up',
  Down = 'down',
}
