/**
 * Gamer One API Documentation
 * Welcome to the Official Gamer One API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@g1.gg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Achievement } from './achievement';
import { Gear } from './gear';
import { LayoutSettings } from './layoutSettings';
import { Product } from './product';
import { SocialNetwork } from './socialNetwork';
import { Sponsor } from './sponsor';
import { User } from './user';
import { NowPlaying } from './nowPlaying';

export interface Profile {
  user: User;
  /**
   * The users social network accounts
   */
  networks: Array<SocialNetwork>;
  /**
   * Collections of sponsors/endorsements the user has, if applicable.
   */
  sponsors: Array<Sponsor>;
  products: Array<Product>;
  currentlyPlaying: NowPlaying;
  layout: LayoutSettings;
  /**
   * User gear
   */
  gears: Array<Gear>;
  /**
   * Users latest 5 achievements
   */
  achievements: Array<Achievement>;
}
