/**
 * Gamer One API Documentation
 * Welcome to the Official Gamer One API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@gamerone.gg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Accepted = 0 | 1;

export enum AcceptedEnum {
  NUMBER_0 = 0,
  NUMBER_1 = 1,
}

export interface SignupRequest {
  email: string;
  password: string;
  username: string;
  firstName?: string;
  lastName?: string;
  /**
   * Whether or not the user accepted terms and conditions checkbox.
   */
  accepted: Accepted;
}
