/**
 * Gamer One API Documentation
 * Welcome to the Official Gamer One API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@gamerone.gg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SponsorRequest {
  /**
   * The name of the sponsor
   */
  name: string;
  /**
   * Image for the sponsor in a binary format
   */
  image: File;
  /**
   * To change the order for the sponsors.
   */
  ordinal?: number;
  /**
   * A valid URL for the sponsor page.
   */
  link: string;
}
