/**
 * Gamer One API Documentation
 * Welcome to the Official Gamer One API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@g1.gg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';

export interface SquadInviteList {
  /**
   * Unique identifier for the squad list
   */
  id: number;
  /**
   * If the request is not accepted, its null. If accepted prints the time for accept date.
   */
  acceptedAt: Date;
  user: User;
}
