/**
 * Gamer One API Documentation
 * Welcome to the Official Gamer One API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@g1.gg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type UnfurlURLType = 'link' | 'photo' | 'video' | 'rich';

export enum UnfurlURLTypeEnum {
  LINK = 'link',
  PHOTO = 'photo',
  VIDEO = 'video',
  RICH = 'rich',
}

export interface UnfurlURL {
  /**
   * Provider url for the given url
   */
  providerUrl: string;
  /**
   * Small description text extracted from the given url
   */
  description: string;
  /**
   * The resource type
   */
  type: UnfurlURLType;
  /**
   * oEmbed version number
   */
  version: string;
  /**
   * Page title for the given url
   */
  title: string;
  /**
   * The name of the author owner of the resource.
   */
  authorName: string;
  /**
   * A URL for the author owner of the resource.
   */
  authorUrl: string;
  /**
   * The name of the resource provider.
   */
  providerName: string;
  /**
   * A URL to a thumbnail image representing the resource. The thumbnail must respect any maxwidth and maxheight parameters. If this parameter is present, thumbnail_width and thumbnail_height must also be present.
   */
  thumbnailUrl: string;
  /**
   * The width of the optional thumbnail. If this parameter is present, thumbnail_url and thumbnail_height must also be present.
   */
  thumbnailWidth: number;
  /**
   * The height of the optional thumbnail. If this parameter is present, thumbnail_url and thumbnail_width must also be present
   */
  thumbnailHeight: number;

  url: string;
}
