/**
 * Gamer One API Documentation
 * Welcome to the Official Gamer One API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@g1.gg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserGearAddRequest {
  /**
   * Name of the gear you want to add
   */
  gear: string;
  /**
   * Gear type id. You can get the list of all types from ref-data calls
   */
  gearTypeId: number;
  link?: string;
  /**
   * Extra information you want to add.
   */
  information: string;
  /**
   * Gear Image.
   */
  image: File;
}
