/**
 * Gamer One API Documentation
 * Welcome to the Official Gamer One API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@gamerone.gg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Club } from './club';
import { ExperienceType } from './experienceType';
import { Game } from './game';

export interface UserExperience {
  id: number;
  title: string;
  companyName?: string | undefined;
  startDate: string;
  endDate: string | null;
  achievements: string;
  game: Game;
  type: ExperienceType;
  club: Club | null;
}
