/**
 * Gamer One API Documentation
 * Welcome to the Official Gamer One API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@gamerone.gg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Game } from './game';
import { GamePlatform } from './gamePlatform';

export interface UserGame {
  /**
   * Relation ID for update and delete operations
   */
  id: number;
  game: Game;
  platform: GamePlatform | null;
  /**
   * Gamertag that user entered while adding game
   */
  gamertag: string | null;
  /**
   * Region that user entered while adding game to their profiles
   */
  region: string | null;
}
